# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  base:
    build:
      context: .
      dockerfile: docker/standup_base
    image: local/standup_base

  web:
    build:
      context: .
      dockerfile: docker/standup_dev
    image: local/standup_dev
    depends_on:
      - base
